### ISSUE TITLE
ambermini conda package still failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/ambermini#22]
I'm still seeing a failure from the tests:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/148/console

It gets as far as `tleap -h` now, so I'm guessing that this is returning a nonzero integer:
https://github.com/omnia-md/conda-recipes/blob/master/ambermini/meta.yaml#L20-L23

**Comment by rmcgibbo** [comment]
might be quicker to build it locally without running the tests, and then run them all, record which ones fail, and then make the necessary changes all at once?

**Comment by swails** [comment]
+1

**Comment by jchodera** [comment]
It's `tleap`:
```
mski1620:conda-recipes jenkins-slave$ ./run.sh "antechamber -h"
antechamber -h
0
mski1620:conda-recipes jenkins-slave$ ./run.sh "sqm -h"
sqm -h
0
mski1620:conda-recipes jenkins-slave$ ./run.sh "tleap -h"
tleap -h
1
```
where `run.sh` is
```bash
#!/bin/bash

echo "$1"

$1 >> log 2>&1 &
pid=$!
wait $!
echo $?
```
