### ISSUE TITLE
Set up appveyor

### ISSUE THREAD

**Issue by jchodera** [choderalab/ambermini#26]
Now that we have windows support thanks to @rmcgibbo via #25

**Comment by rmcgibbo** [comment]
There are no tests though.

**Comment by jchodera** [comment]
There are a modicum of tests to make sure critical packages build without errors, but it's as simple as running the commands with `-h` flags.

**Comment by rmcgibbo** [comment]
Are there any tests upstream?

**Comment by jchodera** [comment]
Presumably, yes.  Maybe we can convince @swails to pull some of those in.

**Comment by rmcgibbo** [comment]
Fixed by #28.
