### ISSUE TITLE
bondtype and atomtype executables complain AMBERHOME is not set

### ISSUE THREAD

**Issue by jchodera** [choderalab/ambermini#32]
While `antechamber` works just fine under `conda`, I just realized `bondtype` and `atomtype` want `$AMBERHOME` set.

**Comment by jchodera** [comment]
@swails: Do I just need to create simple scripts named `bondtype` and `atomtype` following [this `antechamber` script](https://github.com/choderalab/ambermini/blob/master/antechamber/antechamber) and rename the binary targets in [`antechamber/Makefile`](https://github.com/choderalab/ambermini/blob/master/antechamber/Makefile#L10-L11) to have the `_pvt` suffix?  Or is more required?

**Comment by swails** [comment]
What are you doing calling `bondtype` and `atomtype` directly?  These are utility programs called by `antechamber`, and `antechamber` sets `$AMBERHOME`.

**Comment by jchodera** [comment]
I am calling `bondtype` to infer appropriate bond orders from an OpenMM `Topology` object, which does not possess information about bond order.  

Is there a way to get `antechamber` to *just* call out to `bondtype` without doing any additional processing?  I'm currently using 
```
bondtype -i molecule.mol2 -o bonds.ac -f mol2 -j full
```
but most of the fields of the molecule are not properly assigned, so I worried any processing aside from bond type assignment may result in garbage.

**Comment by swails** [comment]
Replacing "private" antechamber programs with wrappers is going to be messy.  If you need to call `bondtype`, try just setting `AMBERHOME` to the Anaconda prefix where it's installed beforehand.

> Is there a way to get antechamber to just call out to bondtype without doing any additional processing? I'm currently using

No idea.  I've never tried it...  But you can see if there are ways to omit stuff like charge derivation in the help or manual.

**Comment by jchodera** [comment]
Looks like I can use
```
antechamber -i molecule.mol2 -fi mol2 -o bonds.ac -fo ac -j 2
```
and get the same effect.

**Comment by swails** [comment]
Right... so let's go that route :smile:

**Comment by jchodera** [comment]
OK!
