### ISSUE TITLE
Update to AmberTools 16

### ISSUE THREAD

**Issue by jchodera** [choderalab/ambermini#36]
This is a discussion of what needs to be done to update `ambermini` to AmberTools 16

From @swails:
> There was a massive reorganization of force fields that happened after I started my new job, and corresponding changes to tleap. The general goal of the FF work was to separate the protein and nucleic acid force fields into separate leaprc files, and files like leaprc.ff14SB were shuffled off into oldff.
>
> I guess what needs to be done is to migrate the changes between AmberTools 15 and AmberTools 16 into ambermini (preferably without getting rid of the fixes for Windows and not having to set AMBERHOME). But that work was a large undertaking and was probably the main reason the release was delayed longer than expected.

Pinging @rafwiewiora who may want to know about this update since it impacts the forcefield conversion.

**Comment by rafwiewiora** [comment]
Thanks!

**Comment by jchodera** [comment]
@swails: We'd love to tackle this update soon. Would you be able to give us some guidance about what we would need to do here?

**Comment by swails** [comment]
I never really had a prescription for this.  Last release, I unpacked AmberTools15.tar.bz2 and copied in all of the files by hand (I used the 'meld' tool to evaluate each change at the file diff level to avoid wiping out the changes that I made specifically for this package to make it standalone).  Then run a few tests to make sure everything continued to work.

It's not a fun process, but I don't think there is enough experience out there to automate it, either.  And this release will be particularly intensive due to the massive force field reshuffling that was done prior to release.

**Comment by hainm** [comment]
@jchodera hopefully ambermini has extensive test to make sure it works correctly.

**Comment by jchodera** [comment]
@hainm: The testing is "do the executables run without crashing?". Beyond that, there is no testing, with the presumption that all testing is already done as part of the Amber development process.

If there is a standard AmberTools test suite that you advise users to run following installation, we can certainly run that as part of the validation process! Just let us know what that is.

**Comment by hainm** [comment]
you might want to add those tests to `ambermini` (They are in $AMBERHOME/AmberTools/test folder)

- antechamber
- leap # critical since ambertools16 has heavy force field reorg.
- sqm

**Comment by jchodera** [comment]
@hainm : I was just looking at an older version of `AmberTools` (still downloading `AmberTools16` for comparison), and it looks like there is an `AmberTools/test/` directory with a `Makefile` that runs a bunch of tests. Running this with the installed `ambermini15` seems to pass most of the tests, failing those for which we didn't package up tools. 

If this still exists in `AmberTools16`, we can simply comment out the tests that don't apply to `ambermini16` and run this as part of the continuous integration process. Would that work?

**Comment by jchodera** [comment]
Aha! Sounds like we're on the same page.

**Comment by jchodera** [comment]
@Lnaden : Looks like we can pull in the `amber16/AmberTools/test/` subdirectory and just comment out any tests from the `Makefile` that don't apply to the packaged tools.

**Comment by j3mdamas** [comment]
@jchodera these still worry me, and I haven't had the chance to look into them:

```
$ diff -rq amber14/dat/leap amber16/dat/leap
Only in amber16/dat/leap/cmd: leaprc.DNA.bsc1
Only in amber16/dat/leap/cmd: leaprc.DNA.OL15
Only in amber14/dat/leap/cmd: leaprc.ff03.r1
Only in amber14/dat/leap/cmd: leaprc.ff03ua
Only in amber14/dat/leap/cmd: leaprc.ff12SB
Only in amber14/dat/leap/cmd: leaprc.ff14ipq
Only in amber14/dat/leap/cmd: leaprc.ff14SB
Only in amber14/dat/leap/cmd: leaprc.ff14SBonlysc
Only in amber16/dat/leap/cmd: leaprc.gaff2
Only in amber14/dat/leap/cmd: leaprc.lipid11
Files amber14/dat/leap/cmd/leaprc.modrna08 and amber16/dat/leap/cmd/leaprc.modrna08 differ
Only in amber14/dat/leap/cmd: leaprc.parmbsc0_chiOL4_ezOL1
Files amber14/dat/leap/cmd/leaprc.phosaa10 and amber16/dat/leap/cmd/leaprc.phosaa10 differ
Only in amber16/dat/leap/cmd: leaprc.protein.fb15
Only in amber16/dat/leap/cmd: leaprc.protein.ff03.r1
Only in amber16/dat/leap/cmd: leaprc.protein.ff03ua
Only in amber16/dat/leap/cmd: leaprc.protein.ff14SB
Only in amber16/dat/leap/cmd: leaprc.protein.ff14SBonlysc
Only in amber16/dat/leap/cmd: leaprc.protein.ff15ipq
Only in amber16/dat/leap/cmd: leaprc.protein.ff15ipq-vac
Only in amber16/dat/leap/cmd: leaprc.RNA.OL3
Only in amber16/dat/leap/cmd: leaprc.RNA.YIL
Only in amber14/dat/leap/cmd: leaprc.spce
Only in amber14/dat/leap/cmd: leaprc.tip3p
Only in amber14/dat/leap/cmd: leaprc.tip4pew
Only in amber16/dat/leap/cmd: leaprc.water.opc
Only in amber16/dat/leap/cmd: leaprc.water.spce
Only in amber16/dat/leap/cmd: leaprc.water.tip3p
Only in amber16/dat/leap/cmd: leaprc.water.tip4pew
Only in amber16/dat/leap/cmd: leaprc.xFPchromophores
Only in amber16/dat/leap/cmd/oldff: leaprc.DNA.bsc0
Only in amber16/dat/leap/cmd/oldff: leaprc.ff14ipq
Only in amber16/dat/leap/cmd/oldff: leaprc.ff14SB
Only in amber16/dat/leap/cmd/oldff: leaprc.lipid11
Only in amber16/dat/leap/cmd/oldff: leaprc.parmbsc0_chiOL4_ezOL1
Only in amber14/dat/leap/cmd/oldff: leaprc.parmCHI_YIL.bsc
Only in amber16/dat/leap/lib: all_aminoctfb15.lib
Only in amber16/dat/leap/lib: all_aminofb15.lib
Only in amber16/dat/leap/lib: all_aminontfb15.lib
Only in amber16/dat/leap/lib: amino15ipq_10.0.lib
Only in amber16/dat/leap/lib: amino15ipq-vac_10.0.lib
Only in amber16/dat/leap/lib: aminocn15ipq_10.0.lib
Only in amber16/dat/leap/lib: aminoct15ipq_10.0.lib
Only in amber16/dat/leap/lib: aminoct15ipq-vac_10.0.lib
Only in amber16/dat/leap/lib: aminont15ipq_10.0.lib
Only in amber16/dat/leap/lib: aminont15ipq-vac_10.0.lib
Only in amber16/dat/leap/lib: DNA.OL15.lib
Only in amber16/dat/leap/lib: fb3box.off
Only in amber16/dat/leap/lib: fb4box.off
Only in amber14/dat/leap/lib: lipid11.lib
Only in amber14/dat/leap/lib: lipid14_supp.lib
Only in amber16/dat/leap/lib/oldff: lipid11.lib
Only in amber16/dat/leap/lib: parmBSC0.lib
Only in amber16/dat/leap/lib: parmBSC1.lib
Only in amber16/dat/leap/lib: phos_amino94.lib
Only in amber14/dat/leap/lib: PTR.lib
Files amber14/dat/leap/lib/residues.RNA.parmCHI_YIL.bsc.lib and amber16/dat/leap/lib/residues.RNA.parmCHI_YIL.bsc.lib differ
Only in amber16/dat/leap/lib: RNA.lib
Only in amber16/dat/leap/lib: RNA.YIL.lib
Only in amber14/dat/leap/lib: S1P.lib
Only in amber14/dat/leap/lib: SEP.lib
Files amber14/dat/leap/lib/solvents.cmd and amber16/dat/leap/lib/solvents.cmd differ
Files amber14/dat/leap/lib/solvents.lib and amber16/dat/leap/lib/solvents.lib differ
Files amber14/dat/leap/lib/solvents.log and amber16/dat/leap/lib/solvents.log differ
Only in amber14/dat/leap/lib: T1P.lib
Only in amber14/dat/leap/lib: TPO.lib
Only in amber16/dat/leap/lib: xFPchromophores.lib
Only in amber14/dat/leap/lib: Y1P.lib
Only in amber16/dat/leap/parm: frcmod.DNA.OL15
Only in amber16/dat/leap/parm: frcmod.fb15
Files amber14/dat/leap/parm/frcmod.ff12SB and amber16/dat/leap/parm/frcmod.ff12SB differ
Files amber14/dat/leap/parm/frcmod.ff14SB and amber16/dat/leap/parm/frcmod.ff14SB differ
Only in amber16/dat/leap/parm: frcmod.ff99bsc0CG
Only in amber16/dat/leap/parm: frcmod.ions1lm_1264_spce
Only in amber16/dat/leap/parm: frcmod.ions1lm_1264_tip3p
Only in amber16/dat/leap/parm: frcmod.ions1lm_1264_tip4pew
Only in amber16/dat/leap/parm: frcmod.ions1lm_126_hfe_opc
Only in amber16/dat/leap/parm: frcmod.ions1lm_126_iod_opc
Only in amber16/dat/leap/parm: frcmod.ions1lm_126_spce
Only in amber16/dat/leap/parm: frcmod.ions1lm_126_tip3p
Only in amber16/dat/leap/parm: frcmod.ions1lm_126_tip4pew
Only in amber16/dat/leap/parm: frcmod.ions1lm_iod
Only in amber14/dat/leap/parm: frcmod.ions1lsm_1264_spce
Only in amber14/dat/leap/parm: frcmod.ions1lsm_1264_tip3p
Only in amber14/dat/leap/parm: frcmod.ions1lsm_1264_tip4pew
Only in amber14/dat/leap/parm: frcmod.ions1lsm_hfe_spce
Only in amber14/dat/leap/parm: frcmod.ions1lsm_hfe_tip3p
Only in amber14/dat/leap/parm: frcmod.ions1lsm_hfe_tip4pew
Only in amber14/dat/leap/parm: frcmod.ions1lsm_iod
Only in amber16/dat/leap/parm: frcmod.ions234lm_1264_spce
Only in amber16/dat/leap/parm: frcmod.ions234lm_1264_tip3p
Only in amber16/dat/leap/parm: frcmod.ions234lm_1264_tip4pew
Only in amber16/dat/leap/parm: frcmod.ions234lm_126_spce
Only in amber16/dat/leap/parm: frcmod.ions234lm_126_tip3p
Only in amber16/dat/leap/parm: frcmod.ions234lm_126_tip4pew
Only in amber16/dat/leap/parm: frcmod.ions234lm_hfe_spce
Only in amber16/dat/leap/parm: frcmod.ions234lm_hfe_tip3p
Only in amber16/dat/leap/parm: frcmod.ions234lm_hfe_tip4pew
Only in amber16/dat/leap/parm: frcmod.ions234lm_iod_spce
Only in amber16/dat/leap/parm: frcmod.ions234lm_iod_tip3p
Only in amber16/dat/leap/parm: frcmod.ions234lm_iod_tip4pew
Only in amber14/dat/leap/parm: frcmod.ions34lsm_1264_spce
Only in amber14/dat/leap/parm: frcmod.ions34lsm_1264_tip3p
Only in amber14/dat/leap/parm: frcmod.ions34lsm_1264_tip4pew
Only in amber14/dat/leap/parm: frcmod.ions34lsm_hfe_spce
Only in amber14/dat/leap/parm: frcmod.ions34lsm_hfe_tip3p
Only in amber14/dat/leap/parm: frcmod.ions34lsm_hfe_tip4pew
Only in amber14/dat/leap/parm: frcmod.ions34lsm_iod_spce
Only in amber14/dat/leap/parm: frcmod.ions34lsm_iod_tip3p
Only in amber14/dat/leap/parm: frcmod.ions34lsm_iod_tip4pew
Only in amber14/dat/leap/parm: frcmod.ionslm_1264_spce
Only in amber14/dat/leap/parm: frcmod.ionslm_1264_tip3p
Only in amber14/dat/leap/parm: frcmod.ionslm_1264_tip4pew
Only in amber14/dat/leap/parm: frcmod.ionslrcm_cm_spce
Only in amber14/dat/leap/parm: frcmod.ionslrcm_cm_tip3p
Only in amber14/dat/leap/parm: frcmod.ionslrcm_cm_tip4pew
Only in amber14/dat/leap/parm: frcmod.ionslrcm_hfe_spce
Only in amber14/dat/leap/parm: frcmod.ionslrcm_hfe_tip3p
Only in amber14/dat/leap/parm: frcmod.ionslrcm_hfe_tip4pew
Only in amber14/dat/leap/parm: frcmod.ionslrcm_iod
Only in amber16/dat/leap/parm: frcmod.parmbsc1
Files amber14/dat/leap/parm/frcmod.parmCHI_YIL and amber16/dat/leap/parm/frcmod.parmCHI_YIL differ
Files amber14/dat/leap/parm/frcmod.phosaa10 and amber16/dat/leap/parm/frcmod.phosaa10 differ
Only in amber16/dat/leap/parm: frcmod.spceb
Only in amber16/dat/leap/parm: frcmod.tip3pfb
Only in amber16/dat/leap/parm: frcmod.tip4pfb
Only in amber16/dat/leap/parm: frcmod.vdWall
Only in amber16/dat/leap/parm: frcmod.xFPchromophores
Only in amber16/dat/leap/parm: gaff2.dat
Files amber14/dat/leap/parm/gaff.dat and amber16/dat/leap/parm/gaff.dat differ
Files amber14/dat/leap/parm/GLYCAM_06j.dat and amber16/dat/leap/parm/GLYCAM_06j.dat differ
Files amber14/dat/leap/parm/lipid14.dat and amber16/dat/leap/parm/lipid14.dat differ
Files amber14/dat/leap/parm/lj_1264_pol.dat and amber16/dat/leap/parm/lj_1264_pol.dat differ
Files amber14/dat/leap/parm/parm10.dat and amber16/dat/leap/parm/parm10.dat differ
Files amber14/dat/leap/parm/parm14ipq.dat and amber16/dat/leap/parm/parm14ipq.dat differ
Only in amber16/dat/leap/parm: parm15ipq_10.3.dat
Only in amber16/dat/leap/parm: validate_torsions.py
```

**Comment by jchodera** [comment]
The AMBER developers regularly update parameter files without versioning them. That's not something we can control for.

**Comment by j3mdamas** [comment]
you are right. if there was some way to test them.

**Comment by jchodera** [comment]
We're going to add execution of the tests provided in AmberTools 16 by the AMBER developers, but I think the changes you are concerned about (revisions to parameter files) are certainly beyond the scope of something we can hope to "test".

**Comment by hainm** [comment]
> $ diff -rq amber14/dat/leap amber16/dat/leap

@j3mdamas this won't be the same due to force field file splitting.
http://ambermd.org/changelog.html

**Comment by j3mdamas** [comment]
you're right. let's just cross our fingers then :p

**Comment by Lnaden** [comment]
@j3mdamas I tried to go through the PR I have open and add all the new FF files (or at least what looked like FF files) to the new version, without removing the old ones. We should be figuring out what needs pruned to avoid old versions hanging around and the package bloating. I think I got most of the files you listed that are in v16 that were not in v14, but I could have missed a few.

**Comment by jchodera** [comment]
> @j3mdamas I tried to go through the PR I have open and add all the new FF files (or at least what looked like FF files) to the new version, without removing the old ones

I think we need to remove files that were removed in v16

**Comment by j3mdamas** [comment]
@Lnaden according to @hainm and the changelog, it seems like removing the old ones is the way to go. we just have to trust that the amber guys did it well. as john said, it's out of our control.

us in htmd are enforcing the version of ambermini with amber15 for now though.

**Comment by Lnaden** [comment]
Will do!

**Comment by hainm** [comment]
@Damas: 

Fyi: https://github.com/pandegroup/openmm/pull/1570#issuecomment-249970641

Hai

**Comment by j3mdamas** [comment]
@hainm thanks for the link!

**Comment by Lnaden** [comment]
I have the PR for AmberMini v16 about as stable as I can make it, #37. If anyone can think of anything else we would want from the main AmberTools let me know. Any other feedback would be helpful too.

Changes:
- Updated all FF files to AmberTools 16
- Updated all libraries in AmberMini to AmberTools 16
- Added `paramfit` program to AmberMini
- Added tests for `antechamber`, `leap`, `sqm`, and `paramfit`
- Added documentation for how to update AmberMini in the future
- Removed old parameter files and commands that are no longer present in AmberTools 16

Legacy AmberMini v15 support:
- Created a branch off exiting HEAD of `master` to allow users to pull down AmberMini v15 for legacy support. Branch is called `AmberMini15`
- Will create target in `omnia` conda channel to point at this version, along with new AmberMini v16 support.

The legacy support will allow us to make hotfixes as needed, although I don't foresee any more active development in that direction.

**Comment by hainm** [comment]
In case you have not added bugfixes: http://ambermd.org/bugfixesat.html

**Comment by Lnaden** [comment]
Good catch, I missed those. I'll patch them in

**Comment by Lnaden** [comment]
Patched in, thanks @hainm!

**Comment by jchodera** [comment]
We should use a versioning mechanism to track which bugfix version we're at. Like `ambermini` 16.16 if we've patched up to bugfix 16 for version 16

**Comment by Lnaden** [comment]
Right now the closest thing we have is the releases, which are on X.Y.Z format which I assume is X=AmberTools Number, Y=??, Z=AmberTools Bugfix Number. 

We also have in the `README.md` file the latest day that this has been built against, but I agree something better is needed.

**Comment by jchodera** [comment]
Our bugfix number previously didn't correspond to the AMBER bugfix number

**Comment by jchodera** [comment]
Suggest we use `X.Y.Z` where
* X = AmberTools version
* Y = AMBER patch number
* Z = our own bugfix number (if we screw something up or add another tool)

**Comment by Lnaden** [comment]
I'd be for that, we don't have a version.py file or something to track it though. We can use github tags pretty easily, although those are a bit less visible to users.

**Comment by jchodera** [comment]
We don't need a version.py. We'd just use this scheme when we cut GitHub and conda releases.

For example, since you merged in all 16 patches, you'd cut a release for 16.16.0 initially. (If you hadn't merged in any patches, you'd cut 16.0.0)

**Comment by Lnaden** [comment]
That works too. I was thinking just keep the GitHub tags as well so we can easily find certain versions. We just flag them as such at release as well.

I'll update the PR with version numbers

**Comment by Lnaden** [comment]
Any more comments on this issue or the PR? There is an issue with appveyor which there are some tools now missing from what looks like the appveyor image itself (flex, bison, rm, etc.). Not quite sure how to fix this since they appear to be tools which have been stripped from the image itself.

**Comment by hainm** [comment]
Hi

Have the missing file stuff when pulling been resolved yet?

**Comment by Lnaden** [comment]
Yeah, I fixed that, it was actually `travis` missing `csh` so none of the test scripts were actually able to run, and I was confused on the error. Near as I can tell, the PR works, its only issue is not part of this PR, but what I think is a larger appveyor problem.

**Comment by Lnaden** [comment]
I think I found it, it looks like the leap tests were updated in patches but I missed them on my second merge pass. We'll see if these new tests pass.

**Comment by Lnaden** [comment]
Would you still like a `make test.all` command in the top test file? Right now the travis tests just invoke each program's set of tests individually.

**Comment by hainm** [comment]
> We'll see if these new tests pass.

ok with my local tests.

**Comment by Lnaden** [comment]
Travis tests are also passing. I won't merge the PR until tomorrow afternoon in case anyone has other feed back on it.

If anyone has other issues with the proposed PR let me know!
