### ISSUE TITLE
How to change sqm.out directory when using antechamber to convert pdb to mol2?

### ISSUE THREAD

**Issue by mainguyenanhvu** [choderalab/ambermini#45]
Hi, 

I want to use antechamber to convert pdb file to mol2 by this command:
```
antechamber -fi pdb -i $work_path/ligand3.pdb -fo mol2 -o $work_path/ligand4.mol2 -c bcc -pf y
```

I would like to place sqm.out in the same directory of mol2. In this case, it needs placing in $work_path directory. 

I do not know how to do this. Please help me. Thank you very much.

**Comment by hainm** [comment]
@mainguyenanhvu  Please ask the question in mailing list: https://ambermd.org/MailingLists.php

**Comment by mainguyenanhvu** [comment]
Thank you very much.
